### ISSUE TITLE
Некоторые замемечания

### ISSUE THREAD

**Issue by SergeyTeplyakov** [dtep/Euler1#1]
1. Надо бы убрать все bin, obj папки с гита. По идее, там gitignore должен был подхватить все это дело сразу.
2. ИМХО, разумнее будет сделать один проект под все задачи project euler-а, там много будет повторяющихся вещей, что позволит использовать код повторно между разными задачами и запускать и проверять их все одним махом. 
3. Посмотри на форматирование. Много лишних пустых строк.
Вот так вот, делать не стоит:

```c#
if ((param % 3) == 0) return true;
            else
                if ((param % 5) == 0) return true;
                else return false;
```

Посколкьу понять код очень сложно. Нужно оборачивать в {}

Метод IsMultiplied, не является обобщенным. Поскольку в нем захардкоджено, на что он должен делиться. Есть вариант, как это сделать очень удобным образом... Пока без спойлеров.

4. Комменты.
Комменты на закрывающих скобках - не приняты. Обычно, если они тебе нужны, то это говорит о не очень хорошем коде.

Ну и нужно подумать, стоит ли делать комменты сразу на английском, чтобы тренировать и его.

Коммент к методу:
```c#
        public static bool IsMultiplied(this int param)
        //Делится ли число нацело на 3 или 5?
```
Должен быть над методом, а не под ним. Возможно, в форме `/// <summary>` если нужно.

4. Еще по стилю

`Console.WriteLine("Sum of all numbers is {0}",sum);`
После запятых ставятся пробелы, чтобы отделить визуально аргументы.

5. Тесты.

Тут есть несколько моментов. Переименовать имя проекта, имя тестового файла.
Потом, тебе нужно именно здесь получить и проверить ответ, а это значит, что логика должна уехать из твоей Program.Main, в какой-то другой класс, например, EulerProblemSolver, с методом SolveProblem1.

**Comment by dtep** [comment]
Вынес решение в отдельный класс в отдельном файле. Сделал функцию универсальной, чтобы принимала переменное число множителей.
